### PR TITLE
Include aliases from completion

### PR DESCRIPTION
**Pull request by derekschrock**
Include aliases for normal command completion.

### CODE REVIEW

**Comment by 0mp** [comment]
Hey! Thank you for your patch! I'll try to take a closer look at it in two weeks, OK?

**Comment by derekschrock** [comment]
Sounds good.  I've been using it for awhile didn't realize it was hosted here and pulled in to the port.  Take your time.

**Comment by derekschrock** [comment]
ping.

**Comment by 0mp** [comment]
Thanks! I'll tag a new release soon.

**Pull request merged**
